# Site settings
title: Ray of Solaris
email: samir@rayofsolaris.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:year/:title
paginate: 5
paginate_path: "/blog/page/:num/"
